name = "nonlinearlstr"
uuid = "21ca2098-f897-4540-9ab3-b13ed390dd37"
authors = ["vcantarella <vcantarella@gmail.com> and contributors"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"


[compat]
julia = "1.10"
LinearAlgebra = "1"
